# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

# When a commit is pushed to the main branch
# Use anothrNick/github-tag-action to determine what the next tag version will be (but should not
# create the tag at this point).   • Store the version as an output for later use
# Using Maven, build and publish your application to GitHub packages
# The version of the published package should match the previously stored version
# Hint: Maven provides a way to update the version from the command line
# Use elgohr/Github-Release-Action to create a GitHub release
# The release message should match the previously stored version
# Workforce Strategy  –  DevOps Challenge
# Summary  –  3
# Hint: Create a new personal access token that has the appropriate entitlements to create
# releases and store this in a secret that can be referenced by the action
# Use anothrNick/github-tag-action to create a tag
# If a commit is pushed to any other branch
# A workflow should not be executed

name: Code Challange

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:   
  build:
    runs-on: ubuntu-latest  
    steps: 
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      id: step1
      uses: anothrNick/github-tag-action@1.36.0
      env:
        WITH_V: true
        DRY_RUN: true
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run:
      # mvn --batch-mode release:update-versions -DevelopmentVersion=${{steps.step1.outputs.tag}}-SNAPSHOT
       mvn -B package --file pom.xml
    outputs:    
        output1: ${{steps.step1.outputs.tag}}
            
  publish:
    runs-on: ubuntu-latest
    name: Publish Release
    needs:  build
    steps:  
    - uses: actions/checkout@master
    - name: Show Tag    
      run: 
       echo Tag is ${{needs.build.outputs.output1}}     
    - name: Create a Release
      uses: elgohr/Github-Release-Action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITFLOWTOKENS }}
      with:
        args: ${{needs.build.outputs.output1}}
    
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITFLOWTOKENS }}
        WITH_V: true
